default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: backend_development
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>

test:
  <<: *default
  database: backend_test
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>
  
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
