
services:
  database:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql
  app:
    build:
      context: backend/.
      args:
        RAILS_ENV: production
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: ${DATABASE_URL}
      RAILS_ENV: production
    ports:
      - "80:80"
      - "3000:3000"
    depends_on:
      - cache
      - database
  cache:
    image: redis:8.4.0
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  postgres_data:
    name: interview-postgres-data
  redis-data:
    name: interview-redis-cache
