---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/companies/{company_id}/question_answers":
    get:
      summary: Lista todos os question_answers
      tags:
      - CompanyQuestionAnswers
      parameters:
      - name: company_id
        in: path
        description: ID da company
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: question_answers encontrados
          content:
            application/json:
              schema:
                type: object
                properties:
                  question_answers:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        created_at:
                          type: string
                        complete?:
                          type: boolean
    post:
      summary: Cria um question_answer
      tags:
      - CompanyQuestionAnswers
      parameters:
      - name: company_id
        in: path
        description: ID da company
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: question_answer criado
        '422':
          description: dados inválidos
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                question_answer:
                  type: object
                  properties:
                    employee_id:
                      type: integer
                    search_id:
                      type: integer
                  required:
                  - employee_id
                  - search_id
  "/api/v1/companies/{company_id}/question_answers/{id}":
    get:
      summary: Retorna um question_answer
      tags:
      - CompanyQuestionAnswers
      parameters:
      - name: company_id
        in: path
        description: ID da company
        required: true
        schema:
          type: integer
      - name: id
        in: path
        description: ID do question_answer
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: question_answer encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  question_answer:
                    type: object
                    properties:
                      id:
                        type: integer
                      created_at:
                        type: string
                      complete?:
                        type: boolean
  "/api/v1/employees/{employee_id}/question_answers":
    get:
      summary: Lista todos os question_answers
      tags:
      - EmployeeQuestionAnswers
      parameters:
      - name: employee_id
        in: path
        description: ID do empregado
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: question_answers encontrados
          content:
            application/json:
              schema:
                type: object
                properties:
                  question_answers:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        created_at:
                          type: string
                        complete?:
                          type: boolean
  "/api/v1/employees/{employee_id}/question_answers/{id}":
    get:
      summary: Retorna um question_answer
      tags:
      - EmployeeQuestionAnswers
      parameters:
      - name: employee_id
        in: path
        description: ID do empregado
        required: true
        schema:
          type: integer
      - name: id
        in: path
        description: ID do question_answer
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: question_answer encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  question_answer:
                    type: object
                    properties:
                      id:
                        type: integer
                      created_at:
                        type: string
                      complete?:
                        type: boolean
    put:
      summary: Atualiza um question_answer
      tags:
      - EmployeeQuestionAnswers
      parameters:
      - name: id
        in: path
        description: ID do question_answer
        required: true
        schema:
          type: integer
      - name: employee_id
        in: path
        description: ID do empregado
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: question_answer atualizado
        '422':
          description: dados inválidos
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                question_answer:
                  type: object
                  properties:
                    employee_id:
                      type: integer
                    question_id:
                      type: integer
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
